sonar.projectKey=maams-ppl_maams-fe_AY3__Q1Hk9qxTTGJIDMw
sonar.host.url=https://sonarqube.cs.ui.ac.id
sonar.projectName=maams-fe
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src/__tests__
sonar.lang.patterns.ts=**/*.ts,**/*.tsx
sonar.lang.patterns.js=**/*.js,**/*.jsx
sonar.exclusions=**/node_modules/**, **/*.d.ts, **/*.js,**/*.jsx, **/__tests__/**
sonar.sourceEncoding=UTF-8

sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
sonar.typescript.lcov.reportPaths=coverage/lcov.info